import { EventEmitter, Injectable } from "@angular/core";
import { Item } from "./item.model";
import { Observable, of } from "rxjs";

@Injectable({
  providedIn: "root",
})
export class ItemService {
  itens: Item[] = [
    /* {
      nome: "",
      imagePath: "../../../../assets/catalogo/",
      nome_cientifico: "",
      nutricao: "",
      temperatura: "",
      ciclo: "",
    }, */

    {
      nome: "Abóbora",
      imagePath: "../../../../assets/catalogo/abobora.jpg",
      nome_cientifico: "Cucurbita moschata Duch",
      nutricao: "vitamina A, cálcio e fósforo",
      temperatura:
        "favorecida por temperaturas elevadas e tolera temperaturas amenas (15º - 25º)",
      ciclo: "90 - 120 dias",
    },
    {
      nome: "Abobrinha",
      imagePath: "../../../../assets/catalogo/abobrinha.jpg",
      nome_cientifico: "Cucurbita pepo L.",
      nutricao: "Niacina, vitamina B",
      temperatura: "Temperatura amenas (15° - 25°)",
      ciclo: "45 - 60 dias",
    },
    {
      nome: "Acelga",
      imagePath: "../../../../assets/catalogo/acelga.jpg",
      nome_cientifico: "Beta vulgaris L. var. cicla",
      nutricao: "Fibras, vitaminas A e C, cálcio, ferro",
      temperatura: "Temperaturas amenas (15° a 25°)",
      ciclo: "60 - 70 dias",
    },
    {
      nome: "Agrião",
      imagePath: "../../../../assets/catalogo/agriao.jpg",
      nome_cientifico: "Nasturtium offinale sp",
      nutricao: "Vitamina C, ferro, iodo",
      temperatura: "Temperaturas amenas (15° - 25°)",
      ciclo: "60 - 70 dias",
    },
    {
      nome: "Alcachofra",
      imagePath: "../../../../assets/catalogo/alcachofra.png",
      nome_cientifico: "Cynara scolymus L.",
      nutricao: "Vitamina C, ácido fólico, magnésio e potássio",
      temperatura: "Temperaturas frias",
      ciclo: "180 - 200 dias",
    },
    {
      nome: "Alface",
      imagePath: "../../../../assets/catalogo/alface.jpg",
      nome_cientifico: "Lactuca sativa L.",
      nutricao: "Cálcio, vitamina A",
      temperatura: "Temperaturas quentes e amenas",
      ciclo: "50 - 80 dias",
    },
    {
      nome: "Alho",
      imagePath: "../../../../assets/catalogo/alho.jpg",
      nome_cientifico: "Allium sativum L.",
      nutricao: "Vitamina B e fosfóro",
      temperatura: "Temperatura frias",
      ciclo: "150 - 180 dias",
    },
    {
      nome: "Almeirao",
      imagePath: "../../../../assets/catalogo/almeirao.jpg",
      nome_cientifico: "Cichorium intybus L.",
      nutricao: "Vitaminas A, B, C, fósforo e ferro",
      temperatura: "Temperaturas amenas (15° - 25°)",
      ciclo: "60 - 70 dias",
    },
    {
      nome: "Batata",
      imagePath: "../../../../assets/catalogo/batata.jpg",
      nome_cientifico: "Solanum tuberosum ssp. tuberosum",
      nutricao: "Vitamina B e fosfóro",
      temperatura: "Temperaturas amenas (15° - 25°)",
      ciclo: "90 - 120 dias",
    },
    {
      nome: "Batata Doce",
      imagePath: "../../../../assets/catalogo/batatadoce.jpg",
      nome_cientifico: "Ipomoea batatas L.",
      nutricao: "Amido e açucares",
      temperatura: "Temperaturas mais elevadas",
      ciclo: "120 - 150 dias",
    },
    {
      nome: "Beringela",
      imagePath: "../../../../assets/catalogo/beringela.jpeg",
      nome_cientifico: "Solanum melongena L.",
      nutricao:
        "vitaminas A, B, C, potássio, fósforo, cálcio, sódio, ferro e enxofre",
      temperatura: "Clima quente",
      ciclo: "100 - 120 dias",
    },
    {
      nome: "Bertalha",
      imagePath: "../../../../assets/catalogo/bertalha.png",
      nome_cientifico: "Basella alba",
      nutricao: "Vitaminas A, C, cálcio, ferro e fósforo",
      temperatura: "Clima quente",
      ciclo: "60 - 70 dias",
    },
    {
      nome: "Beterraba",
      imagePath: "../../../../assets/catalogo/beterraba.jpg",
      nome_cientifico: "Beta vulgaris L.",
      nutricao: "Ferro e açúcar",
      temperatura: "Clima ameno ou frio",
      ciclo: "60 - 70 dias",
    },
    {
      nome: "Brócolis",
      imagePath: "../../../../assets/catalogo/brocolis.jpg",
      nome_cientifico: "Brassica oleracea L.",
      nutricao: "Vitamina C, A, cálcio, ferro, fósforo, fibras",
      temperatura: "Clima ameno",
      ciclo: "90 - 100 dias",
    },
    {
      nome: "Cebola",
      imagePath: "../../../../assets/catalogo/cebola.jpg",
      nome_cientifico: "Allium cepa L.",
      nutricao: "Vitaminas B, C. ",
      temperatura: "Clima quente",
      ciclo: "120 - 180 dias",
    },
    {
      nome: "Cebolinha",
      imagePath: "../../../../assets/catalogo/cebolinha.jpg",
      nome_cientifico: "Allium schoenoprasum L.",
      nutricao: "Cálcio, vitaminas A e C",
      temperatura: "Clima ameno e frio (abaixo de 25°)",
      ciclo: "80 - 100 dias",
    },
    {
      nome: "Cenoura",
      imagePath: "../../../../assets/catalogo/cenoura.jpg",
      nome_cientifico: "Daucus carota L.",
      nutricao: "Cálcio, sódio e potássio",
      temperatura: "Clima ameno (20° a 30°)",
      ciclo: "85 - 100 dias",
    },
    {
      nome: "Chicória",
      imagePath: "../../../../assets/catalogo/chicoria.jpg",
      nome_cientifico: "Cichorium endivia L.",
      nutricao: "Fibras, vitaminas, potássio",
      temperatura: "Clima ameno (15° - 25°)",
      ciclo: "60 - 70 dias",
    },
    {
      nome: "Chuchu",
      imagePath: "../../../../assets/catalogo/chuchu.jpg",
      nome_cientifico: "Sechium edule Sw.",
      nutricao: "Fibras, vitaminas A, B, C e potássio",
      temperatura: "Clima ameno (15° - 25°)",
      ciclo: "100 - 120 dias",
    },
    {
      nome: "Coentro",
      imagePath: "../../../../assets/catalogo/coentro.jpg",
      nome_cientifico: "Coriandrum sativum L.",
      nutricao: "Vitaminas A, B, C",
      temperatura: "Clima quente",
      ciclo: "50 - 60 dias",
    },
    {
      nome: "Couve",
      imagePath: "../../../../assets/catalogo/couve.jpg",
      nome_cientifico: "Brassica oleracea L.",
      nutricao: "Cálcio, ferro, vitaminas A, B, C, K",
      temperatura: "Clima ameno",
      ciclo: "80 - 90 dias",
    },
    {
      nome: "Couve-flor",
      imagePath: "../../../../assets/catalogo/couveflor.jpg",
      nome_cientifico: "Brassica oleracea var.",
      nutricao: "Vitamina C, cálcio, fosfóro",
      temperatura: "Clima ameno e quente",
      ciclo: "90 - 110 dias",
    },
    {
      nome: "Ervilha",
      imagePath: "../../../../assets/catalogo/ervilha.jpg",
      nome_cientifico: "Pisum sativum L.",
      nutricao: "vitaminas A, B, C, fibras",
      temperatura: "Clima ameno e frio (abaixo de 25°)",
      ciclo: "60 - 70 dias",
    },
    {
      nome: "Espinafre",
      imagePath: "../../../../assets/catalogo/espinafre.jpg",
      nome_cientifico: "Spinacea oleracea L.",
      nutricao: "Vitamina A, ferro",
      temperatura: "Clima ameno (15° - 25°)",
      ciclo: "60 - 80 dias",
    },
    {
      nome: "Feijão Vagem",
      imagePath: "../../../../assets/catalogo/feijaovagem.jpg",
      nome_cientifico: "Phaseolus vulgaris L.",
      nutricao: "Proteína",
      temperatura: "Clima ameno e quente",
      ciclo: "60 - 70 dias",
    },
    {
      nome: "Gengibre",
      imagePath: "../../../../assets/catalogo/gengibre.jpg",
      nome_cientifico: "Zingiber offininale Roscoe",
      nutricao: "Vitaminas A, B, C, potássio, sódio",
      temperatura: "Clima ameno e quente",
      ciclo: "240 - 300 dias",
    },
    {
      nome: "Inhame",
      imagePath: "../../../../assets/catalogo/inhame.jpg",
      nome_cientifico: "Dioscorea alata L.",
      nutricao: "Vitamina B, carboidrato",
      temperatura: "Clima quente",
      ciclo: "150 - 180 dias",
    },
    {
      nome: "Jiló",
      imagePath: "../../../../assets/catalogo/jilo.jpg",
      nome_cientifico: "Solanum gilo Raddi",
      nutricao: "Vitaminas A, B, cálcio, fósforo, ferro",
      temperatura: "Clima ameno e quente",
      ciclo: "90 - 100 dias",
    },
    {
      nome: "Mandioquinha Salsa",
      imagePath: "../../../../assets/catalogo/mandioquinhasalsa.jpg",
      nome_cientifico: "Arracacia xanthorrhiza Banc.",
      nutricao: "Vitamina B e carboidratos",
      temperatura: "Clima ameno",
      ciclo: "300 - 360 dias",
    },
    {
      nome: "Maxixe",
      imagePath: "../../../../assets/catalogo/maxixe.jpg",
      nome_cientifico: "Cucumis angurria L.",
      nutricao: "Zinco",
      temperatura: "Clima quente",
      ciclo: "60 - 70 dias",
    },
    {
      nome: "Melancia",
      imagePath: "../../../../assets/catalogo/melancia.jpg",
      nome_cientifico: "Citrullus lanatus",
      nutricao: "Vitaminas A e C",
      temperatura: "Clima quente",
      ciclo: "85 - 90 dias",
    },
    {
      nome: "Melão",
      imagePath: "../../../../assets/catalogo/melao.jpg",
      nome_cientifico: "Cucumis melo L.",
      nutricao: "Vitaminas A e C",
      temperatura: "Clima quente",
      ciclo: "80 - 120 dias",
    },
    {
      nome: "Milho",
      imagePath: "../../../../assets/catalogo/milho.jpg",
      nome_cientifico: "Zea mays L.",
      nutricao: "Açúcar, amido",
      temperatura: "Clima quente e ameno",
      ciclo: "80 - 110 dias",
    },
    {
      nome: "Moranga",
      imagePath: "../../../../assets/catalogo/moranga.jpg",
      nome_cientifico: "Cucurbita maxima Duch",
      nutricao: "Vitamina A e carboidratos",
      temperatura: "Clima ameno e quente",
      ciclo: "120 - 150 dias",
    },
    {
      nome: "Morango",
      imagePath: "../../../../assets/catalogo/morango.jpg",
      nome_cientifico: "Fragaria X ananassa Duch.",
      nutricao: "Vitaminas A, C",
      temperatura: "Clima frio e ameno",
      ciclo: "70 - 80 dias",
    },
    {
      nome: "Mostarda",
      imagePath: "../../../../assets/catalogo/mostarda.jpg",
      nome_cientifico: "Brassica juncea",
      nutricao: "Vitaminas A, C, cálcio, ferro, sódio, potássio, magnésio",
      temperatura: "Clima ameno (15° - 25°)",
      ciclo: "45 - 50 dias",
    },
    {
      nome: "Nabo",
      imagePath: "../../../../assets/catalogo/nabo.jpg",
      nome_cientifico: "Brassica rapa var. rapa (L.) Thell.",
      nutricao: "Cálcio",
      temperatura: "Clima ameno (15° - 25°)",
      ciclo: "50 - 60 dias",
    },
    {
      nome: "Pepino",
      imagePath: "../../../../assets/catalogo/pepino.jpg",
      nome_cientifico: "Cucumis sativus L.",
      nutricao: "Vitaminas A, B, C, potássio",
      temperatura: "Clima ameno e quente",
      ciclo: "45 - 60 dias",
    },
    {
      nome: "Pimenta",
      imagePath: "../../../../assets/catalogo/pimenta.jpg",
      nome_cientifico: "Capsicum frutescens L.",
      nutricao: "Vitaminas A, B, C",
      temperatura: "Clima quente",
      ciclo: "90 - 120 dias",
    },
    {
      nome: "Pimentão",
      imagePath: "../../../../assets/catalogo/pimentao.jpg",
      nome_cientifico: "Capsicum annuum L.",
      nutricao: "Vitaminas A, C",
      temperatura: "Clima quente e ameno",
      ciclo: "100 - 120 dias",
    },
    {
      nome: "Quiabo",
      imagePath: "../../../../assets/catalogo/quiabo.jpg",
      nome_cientifico: "Abelmoschus esculentus (L.) Moench",
      nutricao: "Vitaminas A, B, C",
      temperatura: "Clima quente",
      ciclo: "70 - 80 dias",
    },
    {
      nome: "Rabanete",
      imagePath: "../../../../assets/catalogo/rabanete.jpg",
      nome_cientifico: "Raphanus sativus L.",
      nutricao: "Vitamina C, fibras",
      temperatura: "Clima ameno e frio",
      ciclo: "25 - 30 dias",
    },
    {
      nome: "Repolho",
      imagePath: "../../../../assets/catalogo/repolho.jpg",
      nome_cientifico: "Brassica oleracea L.",
      nutricao: "Fibras, vitaminas B, E, K",
      temperatura: "Clima ameno",
      ciclo: "90 - 110 dias",
    },
    {
      nome: "Rúcula",
      imagePath: "../../../../assets/catalogo/rucula.jpg",
      nome_cientifico: "Eruca sativa L.",
      nutricao: "Ferro, cálcio, fósforo, vitaminas A, C",
      temperatura: "40 - 60 dias",
      ciclo: "",
    },
    {
      nome: "Salsa",
      imagePath: "../../../../assets/catalogo/salsa.png",
      nome_cientifico: "Petroselinum crispum (Mill.) Nym.",
      nutricao: "Vitamina A",
      temperatura: "Clima ameno (15° - 25)",
      ciclo: "60 - 70 dias",
    },
    {
      nome: "Taioba",
      imagePath: "../../../../assets/catalogo/taioba.jpg",
      nome_cientifico: "Xanthosoma sagittifolium (L.) Schott",
      nutricao: "Vitamina A, cálcio, fosfóro",
      temperatura: "Clima quente",
      ciclo: "70 - 100 dias",
    },
    {
      nome: "Taro",
      imagePath: "../../../../assets/catalogo/taro.jpg",
      nome_cientifico: "Colocasia esculenta (L.) Schott",
      nutricao: "Carboidratos, ferro, fósforo",
      temperatura: "Clima quente",
      ciclo: "150 - 180 dias",
    },
    {
      nome: "Tomate",
      imagePath: "../../../../assets/catalogo/tomate.jpg",
      nome_cientifico: "Lycopersicon esculentum Mill.",
      nutricao: "Vitaminas A, C e potássio",
      temperatura: "Clima ameno (15° - 25°)",
      ciclo: "100 - 120 dias",
    },
  ];
  getItens() {
    return this.itens.slice(); // Simulando um retorno de Observable
  }

  fichaSelecionada = new EventEmitter<Item>();
}
